version: '3.8'

services:
  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    image: 654654198246.dkr.ecr.us-east-1.amazonaws.com/entrega-devops-backend-ventas:latest

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    image: 654654198246.dkr.ecr.us-east-1.amazonaws.com/entrega-devops-backend-despachos:latest

  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    image: 654654198246.dkr.ecr.us-east-1.amazonaws.com/entrega-devops-frontend:latest