# Multistage
# Stage 1: se encargará de crear el .jar
FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /build

COPY pom.xml .

COPY src ./src

RUN mvn clean package -DskipTests

# Stage 2: ejecutar la api
FROM eclipse-temurin:17-jdk
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /build/target/*.jar app.jar
COPY entrypoint.sh /app/entrypoint.sh

# MUY IMPORTANTE: Dar permisos de ejecución al script
RUN chmod +x /app/entrypoint.sh

EXPOSE 8080
# Ahora el ENTRYPOINT ejecuta el script, no el jar directamente
ENTRYPOINT ["./entrypoint.sh"]