#Despliegue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend_ventas
  template:
    metadata:
      labels:
        app: backend_ventas
    spec:
      containers:
        - name: backend_ventas
          image: 339713057785.dkr.ecr.us-east-1.amazonaws.com/backend-ventas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/gamecatalog
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
#Service:
apiVersion: v1
kind: Service
metadata:
  name: backend_ventas
spec:
  selector:
    app: backend_ventas
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP