apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  db-root-password: "secreto123"
  db-name: "db_itpcargo"         
  db-username: "root"
  db-url: "jdbc:mysql://mysql:3306/db_itpcargo?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
  aws-region: "us-east-1"
  eks-cluster-name: "entrega-devops-cluster"